### ISSUE TITLE
Developing methods for the state.dia classes

### ISSUE THREAD

**Issue by Erwan-BR** [Erwan-BR/PLT#24]
# Purpose of the issue
For each class, we now need to code how the real methods work.

To do this, we'll have to divide up the tasks:

## Code method (update state.dia id necessary)

- [x] Code method for the Game class (@Xblaze37)
- [x] Code method for the Player class (@Hakamatsu)
- [x] Code method for the Card class 
- [x] Code method for the DevelopmentCard class (@Erwan-BR)
- [x] Code method for the EmpireCard class

## Rules
To simplify debugging, code rereading and unit testing, it's important to **follow several rules**:
- Correctly comment your code.
- Think about worflow.
- Give explicit names to all variables.
- Free pointers if necessary.

**Comment by AMillasseau** [comment]
Can I get a method getter on the attribute resourceProducing on Game Class:
ResourceType getResourceProducing()

Ty

**Comment by Erwan-BR** [comment]
@AMillasseau done and merged.
