### ISSUE TITLE
Add AI to the game

### ISSUE THREAD

**Issue by AMillasseau** [Erwan-BR/PLT#50]
# Purpose of the issue
For the game, we now need to code three different types of AI.

We'll have to give the AIs this three behaviors :

## AI Behavior (located in src/shared/ai)
- [x] Random AI. Random AI will take any decision randomly. (@Erwan-BR)
- [x] Advanced AI. Advanced AI will have a strategy already determined and supposed to make it win. Then it will try to follow this strategy. (@Xblaze37)

**Comment by Erwan-BR** [comment]
Currently, random AI are playing to the game.
